version: '3.8'

services:
  webhook-service:
    build: .
    container_name: nocodb-webhook
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - NC_BASE_URL=http://nocodb:8080
      - NC_TOKEN=nc_pat_xxxx
      - BASE_ID=pheeswfbk3ay3et
      - TARGET_TABLE_ID=m7gmgfij532711w
      - FIXED_TARGET_RECORD_ID=1
    networks:
      - nocodb
    # 如果你想通过宿主机 IP 访问这个 webhook，保留 ports
    # 如果只通过 Nginx 转发，可以考虑只暴露给网络
    ports:
      - "5000:5000"

networks:
  # 声明使用已经存在的 nocodb 网络
  nocodb:
    external: true